/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, {Component} from 'react';
import {StyleSheet, Text, View} from 'react-native';
import {ModelView} from 'rn-avr-model-view';

export class App extends Component {
  constructor(props) {
    super(props);

    this.state = {
      message: null,
    };
  }

  onLoadModelStart = () => {
    this.setState({message: 'Loading model...'});
    console.log('[react-native-3d-model-view]:', 'Load model start.');
  };

  onLoadModelSuccess = () => {
    this.setState({message: 'Loading model success!'});
    console.log('[react-native-3d-model-view]:', 'Load model success.');
  };

  onLoadModelError = error => {
    this.setState({message: 'Loading model error :('});
    console.log('[react-native-3d-model-view]:', 'Load model error.');
  };
  render() {
    return (
      <View style={styles.container}>
        <View style={styles.modelContainer}>
          <Text>{this.state.message}</Text>
          <ModelView
            ref={modelView => {
              this.modelView = modelView;
            }}
            style={styles.modelView}
            source={{
            zip: 'https://embed.avr.asia/demo/sofa01/Sofa_01.zip',
              // zip:
              //   'https://github.com/BonnierNews/react-native-3d-model-view/blob/master/example/obj/Hamburger.zip?raw=true',
              // unzippedFolderName: 'Hamburger',
            }}
            onLoadModelStart={this.onLoadModelStart}
            onLoadModelSuccess={this.onLoadModelSuccess}
            onLoadModelError={this.onLoadModelError}
          />
        </View>
      </View>
    );
  }
}

export default App;

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modelContainer: {
    padding: 10,
    width: '100%',
  },
  modelView: {
    width: '100%',
    height: 300,
    backgroundColor: 'white',
  },
  buttonContainer: {
    paddingVertical: 10,
  },
});
